{
 "title": "JWT Pizza Dashboard",
 "description": "All metrics for deliverable 8",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Logs (Verbose)",
   "type": "logs",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{component=\"jwt-pizza-service\"}"
    }
   ]
  },
  {
   "title": "Logs (Table)",
   "type": "table",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "description": "Users that are currently logged in",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "auth_numActive{source=\"jwt-pizza-service\"}",
     "legendFormat": "Number of Users"
    }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "rate(auth_successfulLogins{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(auth_unsuccessfulAuthCalls{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hardware_memoryUsagePercentage{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Percentage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hardware_cpuUsagePercentage{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizzas Sold",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "rate(purchase_pizzasSold{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Pizza Purchases / min"
    },
    {
     "expr": "rate(purchase_creationFailures{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Purchase Failures / min"
    }
   ]
  },
  {
   "title": "Total Revenue",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(purchase_totalRevenue{source=\"jwt-pizza-service\"}[24h])",
     "legendFormat": "Revenue"
    }
   ]
  },
  {
   "title": "Pizza Creation Latency (Sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "latency_creationLatency{source=\"jwt-pizza-service\"}",
     "legendFormat": "Creation Latency"
    }
   ]
  },
  {
   "title": "Service Endpoint Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "latency_serviceLatency{source=\"jwt-pizza-service\"}",
     "legendFormat": "Service Endpoint Latency"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "description": "PUT, DELETE, GET, POST, PUT requests and ALL combined",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "rate(requests_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "TOTAL"
    },
    {
     "expr": "rate(requests_get{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "GET"
    },
    {
     "expr": "rate(requests_post{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "POST"
    },
    {
     "expr": "rate(requests_delete{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "DELETE"
    },
    {
     "expr": "rate(requests_put{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "PUT"
    }
   ]
  }
 ]
}